settings:
    running: 1
    revert_penalty: 350
    webserver_ip: 10.1.0.4
    polling:
        interval: 30
        jitter: 0
        timeout: 20
    pcr:
        approval_window: 0
        service_interval: 2
        service_jitter: 1

web_admins:
        admin: SpeakAndSpell

teams:
    Team1:
        team_num: 1
        user:
            username: team1
            password: FightingFish
    Team2:
        team_num: 2
        user:
            username: team2
            password: KeepAlive
    Team3:
        team_num: 3
        user:
            username: team3
            password: DropOver
    Team4:
        team_num: 4
        user:
            username: team4
            password: WaterTight

vapps:
    Mock2_2018-10-21:
        subnet: "10.0.{}.0"
        netmask: 255.255.255.0
        systems:
            pfSense:
                host: 1
            Lab01:
                host: 10
                checks:
                    Lab01-ssh:
                        type: ssh
                        port: 22
                        checker: output_check
                        ios:
                            lab01-ssh:
                                input:
                                    task: dirname `pwd`
                                output: 
                                    output: /home
            WWW:
                host: 20
                checks:
                    WWW-http:
                        type: http
                        port: 80
                        checker: diff_match
                        ios:
                            www-http:
                                input:
                                    proto: http
                                    path: ""
                                    host: www.goats.lan
                                output:
                                    tolerance: 0.05
                                    file: www.html
            MySQL:
                host: 30
                checks:
                    MySQL-mysql:
                        type: mysql
                        port: 3306
                        checker: match_sql_output
                        ios:
                            mysql:
                                input:
                                    db: students
                                    query: SELECT phone FROM students WHERE student_id=96
                                output:
                                    output: 962-849-6753
            Mail:
                host: 40
                checks:
                    Mail-imap:
                        type: imap
                        port: 143
                        checker: authenticated
                        ios:
                            mail-imap:
                                input:
                                    starttls: True
                                output:
                    Mail-smtp:
                        type: smtp
                        port: 25
                        checker: sent_successfully
                        ios:
                            mail-smtp:
                                input:
                                    fqdn: goats.lan
                                    users:
                                        - bertha.compton
                                        - veronica.rowe
                                        - richard.tyler
                                        - julie.fuller
                                    message: Hey there
                                output:
            OwnCloud:
                host: 50
                checks:
                    OwnCloud-http:
                        type: http
                        port: 80
                        checker: diff_match
                        ios:
                            owncloud-http:
                                input:
                                    proto: http
                                    path: index.php/login
                                    host: owncloud.goats.lan
                                output:
                                    tolerance: 0.05
                                    file: owncloud.html
            Lab02:
                host: 60
                checks:
                    Lab02-ftp:
                        type: ftp
                        port: 21
                        checker: hash_match
                        ios:
                            lab02-ftp:
                                input:
                                    filepath: Syllabi/English12.pdf
                                output:
                                    hash: 61e85643cd4b4c977444909f6de11e5b0643dcdf
                    Lab02-ssh:
                        type: ssh
                        port: 22
                        checker: output_check
                        ios:
                            lab02-ssh:
                                input:
                                    task: dirname `pwd`
                                output:
                                    output: /home
            DC01:
                host: 70
                checks:
                    DC01-ldap:
                        type: ldap
                        port: 389
                        checker: match_ldap_output
                        ios:
                            dc01-ldap:
                                input:
                                    base: cn=Users,dc=GOATS,dc=LAN
                                    filter: (sAMAccountName=dwayne.avery)
                                    attributes: [objectGUID]
                                output:
                                    objectGUID: [UG2mgvq9G06Ca6bNtAnINg==]
                    DC01-dns:
                        type: dns
                        port: 53
                        checker: any_match
                        ios:
                            dns-www:
                                input:
                                    record_type: A
                                    query: www.goats.lan
                                output:
                                    answer: [20]
                            dns-owncloud:
                                input:
                                    record_type: A
                                    query: owncloud.goats.lan
                                output:
                                    answer: [50]
                            dns-moodle:
                                input:
                                    record_type: A
                                    query: moodle.goats.lan
                                output:
                                    answer: [100]
            DC02:
                host: 80
                checks:
                    DC02-ldap:
                        type: ldap
                        port: 389
                        checker: match_ldap_output
                        ios:
                            dc02-ldap:
                                input:
                                    base: cn=Users,dc=GOATS,dc=LAN
                                    filter: (sAMAccountName=brent.head)
                                    attributes: [objectGUID]
                                output:
                                    objectGUID: [SjMmjuiQA02/lRXxeISH6A==]
            MSSQL:
                host: 90
                checks:
                    MSSQL-mssql:
                        type: mssql
                        port: 1433
                        checker: match_sql_output
                        ios:
                            mssql:
                                input:
                                    db: staff
                                    query: SELECT dob FROM staff WHERE emp_id=85
                                output:
                                    output: "1980-04-26"
            Moodle:
                host: 100
                checks:
                    Moodle-http:
                        type: http
                        port: 80
                        checker: diff_match
                        ios:
                            moodle-http:
                                input:
                                    proto: http
                                    path: ""
                                    host: moodle.goats.lan
                                output:
                                    tolerance: 0.05
                                    file: moodle.html
            Share:
                host: 110
                checks:
                    Share-smb:
                        type: smb
                        port: 445
                        checker: hash_match
                        ios:
                            share-smb:
                                input:
                                    hostname: Share
                                    sharename: share
                                    path: 18-19newsletter.pdf
                                output:
                                    hash: 933520ae6fbafecb65c16763838491376c4299a8
            Win7:
                host: 120
                checks:
                    Win7-rdp:
                        type: rdp
                        port: 3389
                        checker: authenticated
                        ios:
                            win7-rdp:
                                input:
                                output:

credentials:
    default_password: Password1!
    local:
        monique.cooper:
            ios: ['lab01-ssh', 'lab02-ssh']
        geneva.sweeney:
            ios: ['lab01-ssh', 'mail-imap']
        lawrence.branch:
            ios: ['lab01-ssh', 'lab02-ftp', 'lab02-ssh']
        tricia.zamora:
            ios: ['lab01-ssh', 'lab02-ftp', 'mail-imap']
        cora.pittman:
            ios: ['lab01-ssh']
        wanda.cleveland:
            ios: ['lab01-ssh', 'lab02-ftp']
        cesar.singleton:
            ios: ['lab01-ssh', 'mail-imap']
        rose.moses:
            ios: ['lab01-ssh']
        tricia.rogers:
            ios: ['lab01-ssh', 'lab02-ftp', 'lab02-ssh']
        ashley.porter:
            ios: ['lab01-ssh', 'lab02-ftp', 'lab02-ssh', 'mail-imap']
        jeanette.owens:
            ios: ['lab01-ssh', 'mail-imap']
        richard.tyler:
            ios: ['lab01-ssh', 'lab02-ssh', 'mail-imap']
        cindy.tran:
            ios: ['lab01-ssh', 'lab02-ssh', 'mail-imap']
        brent.head:
            ios: ['lab01-ssh', 'mail-imap']
        lance.blanchard:
            ios: ['lab01-ssh', 'lab02-ftp', 'lab02-ssh', 'mail-imap']
        bertha.compton:
            ios: ['lab01-ssh', 'lab02-ftp', 'lab02-ssh']
        perry.holt:
            ios: ['lab01-ssh', 'mail-imap']
        cristina.christensen:
            ios: ['lab01-ssh', 'lab02-ftp']
        lawrence.henderson:
            ios: ['lab01-ssh', 'lab02-ftp', 'lab02-ssh']
        erick.houston:
            ios: ['lab01-ssh', 'lab02-ftp', 'lab02-ssh']
        mae.gaines:
            ios: ['lab01-ssh']
        jody.sutton:
            ios: ['lab01-ssh', 'lab02-ssh']
        monique.foreman:
            ios: ['lab01-ssh', 'lab02-ssh']
        brett.howard:
            ios: ['lab01-ssh', 'lab02-ftp', 'lab02-ssh', 'mail-imap']
        sophia.norton:
            ios: ['lab01-ssh', 'lab02-ssh']
        catherine.hays:
            ios: ['lab02-ftp', 'mail-imap']
        dean.blackburn:
            ios: ['lab02-ftp', 'mail-imap']
        veronica.rowe:
            ios: ['lab02-ftp', 'mail-imap']
        bonita.velasquez:
            ios: ['lab02-ftp', 'mail-imap']
        benny.hopper:
            ios: ['lab02-ftp', 'mail-imap']
        shelly.henderson:
            ios: ['lab02-ftp']
        anne.reese:
            ios: ['lab02-ftp']
        ed.solomon:
            ios: ['lab02-ftp', 'mail-imap']
        viola.schroeder:
            ios: ['lab02-ftp', 'mail-imap']
        rachael.tillman:
            ios: ['lab02-ftp', 'lab02-ssh']
        julie.fuller:
            ios: ['lab02-ftp', 'mail-imap']
        calvin.charles:
            ios: ['lab02-ftp', 'lab02-ssh', 'mail-imap']
        ruby.singleton:
            ios: ['lab02-ftp', 'lab02-ssh', 'mail-imap']
        elsie.sykes:
            ios: ['lab02-ftp']
        antonio.le:
            ios: ['lab02-ssh']
        roberto.simon:
            ios: ['lab02-ssh']
        jenna.chambers:
            ios: ['lab02-ssh']
        owen.patrick:
            ios: ['lab02-ssh', 'mail-imap']
        heather.nolan:
            ios: ['lab02-ssh']
        richard.franks:
            ios: ['lab02-ssh', 'mail-imap']
        dwayne.avery:
            ios: ['lab02-ssh', 'mail-imap']
        lesley.russell:
            ios: ['lab02-ssh']
        toni.mosley:
            ios: ['mail-imap']
    domain:
        GOATS.LAN:
            cristina.christensen:
                ios: ['dc01-ldap', 'share-smb', 'win7-rdp']
            lance.blanchard:
                ios: ['dc01-ldap', 'dc02-ldap', 'share-smb', 'win7-rdp']
            heather.nolan:
                ios: ['dc01-ldap', 'share-smb', 'win7-rdp']
            monique.cooper:
                ios: ['dc01-ldap', 'dc02-ldap', 'win7-rdp']
            richard.tyler:
                ios: ['dc01-ldap', 'dc02-ldap', 'share-smb', 'win7-rdp']
            antonio.le:
                ios: ['dc01-ldap', 'dc02-ldap', 'share-smb', 'win7-rdp']
            anne.reese:
                ios: ['dc01-ldap']
            wanda.cleveland:
                ios: ['dc01-ldap', 'dc02-ldap', 'share-smb', 'win7-rdp']
            rachael.tillman:
                ios: ['dc01-ldap', 'dc02-ldap', 'share-smb', 'win7-rdp']
            perry.holt:
                ios: ['dc01-ldap']
            owen.patrick:
                ios: ['dc01-ldap', 'share-smb']
            roberto.simon:
                ios: ['dc01-ldap', 'share-smb', 'win7-rdp']
            cesar.singleton:
                ios: ['dc01-ldap', 'dc02-ldap']
            jenna.chambers:
                ios: ['dc01-ldap', 'share-smb']
            ruby.singleton:
                ios: ['dc01-ldap', 'dc02-ldap', 'win7-rdp']
            cora.pittman:
                ios: ['dc01-ldap', 'dc02-ldap']
            veronica.rowe:
                ios: ['dc01-ldap']
            geneva.sweeney:
                ios: ['dc01-ldap']
            cindy.tran:
                ios: ['dc01-ldap', 'win7-rdp']
            lesley.russell:
                ios: ['dc01-ldap', 'dc02-ldap']
            richard.franks:
                ios: ['dc01-ldap', 'dc02-ldap']
            lawrence.branch:
                ios: ['dc01-ldap']
            monique.foreman:
                ios: ['dc01-ldap', 'win7-rdp']
            erick.houston:
                ios: ['dc01-ldap', 'share-smb', 'win7-rdp']
            melvin.lopez:
                ios: ['dc01-ldap', 'share-smb']
            tricia.zamora:
                ios: ['dc02-ldap']
            toni.mosley:
                ios: ['dc02-ldap', 'share-smb']
            viola.schroeder:
                ios: ['dc02-ldap', 'share-smb']
            julie.fuller:
                ios: ['dc02-ldap', 'share-smb', 'win7-rdp']
            dean.blackburn:
                ios: ['dc02-ldap']
            dwayne.avery:
                ios: ['dc02-ldap']
            jeanette.owens:
                ios: ['dc02-ldap', 'share-smb', 'win7-rdp']
            sophia.norton:
                ios: ['dc02-ldap', 'share-smb', 'win7-rdp']
            rose.moses:
                ios: ['dc02-ldap']
            ed.solomon:
                ios: ['dc02-ldap', 'share-smb', 'win7-rdp']
            lawrence.henderson:
                ios: ['dc02-ldap', 'share-smb']
            tricia.rogers:
                ios: ['dc02-ldap', 'win7-rdp']
            mae.gaines:
                ios: ['dc02-ldap', 'share-smb']
            benny.hopper:
                ios: ['dc02-ldap', 'win7-rdp']
            jody.sutton:
                ios: ['share-smb']
            catherine.hays:
                ios: ['share-smb', 'win7-rdp']
            emma.hensley:
                ios: ['share-smb']
            brent.head:
                ios: ['share-smb']
            bonita.velasquez:
                ios: ['share-smb', 'win7-rdp']
            elsie.sykes:
                ios: ['win7-rdp']
            calvin.charles:
                ios: ['win7-rdp']
            bertha.compton:
                ios: ['win7-rdp']
            brett.howard:
                ios: ['win7-rdp']
