                    name-pop:
                        type: pop
                        port: 110
                        checker: authenticated
                        ios:
                            name-pop:
                                input:
                                    starttls: True
                                output:
