                    name-rdp:
                        type: rdp
                        port: 3389
                        checker: authenticated
                        ios:
                            name-rdp:
                                input:
                                output:
